-- create_attendance_tables.sql
-- Supabase / PostgreSQL migration to add attendance tracking tables
-- Run in Supabase SQL editor or via psql connected to your project's DB

-- 1) event_registrations: When users register for an event (generates a registration_token)
CREATE TABLE IF NOT EXISTS public.event_registrations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id bigint NOT NULL,
  full_name text NOT NULL,
  barangay text NOT NULL,
  contact text,
  email text,
  notes text,
  registration_token text NOT NULL UNIQUE,
  registered_at timestamptz DEFAULT now() NOT NULL,
  attended boolean DEFAULT false NOT NULL,
  attended_at timestamptz,
  marked_by bigint, -- references admin user who marked (if applicable)
  created_at timestamptz DEFAULT now() NOT NULL
);

-- Add FK to events table if it exists
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints 
                 WHERE constraint_name = 'fk_event_registrations_event' AND table_name = 'event_registrations') THEN
    ALTER TABLE public.event_registrations
      ADD CONSTRAINT fk_event_registrations_event
      FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;
  END IF;
END $$;

-- Optional: FK to users table for marker
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints 
                 WHERE constraint_name = 'fk_event_registrations_marked_by' AND table_name = 'event_registrations') THEN
    ALTER TABLE public.event_registrations
      ADD CONSTRAINT fk_event_registrations_marked_by
      FOREIGN KEY (marked_by) REFERENCES public.sk_users(id);
  END IF;
END $$;

-- Index to speed lookups by token
CREATE INDEX IF NOT EXISTS idx_event_registrations_token ON public.event_registrations (registration_token);
CREATE INDEX IF NOT EXISTS idx_event_registrations_event_id ON public.event_registrations (event_id);

-- 2) attendances: Generic attendance records (guest/manual or scanned entries)
CREATE TABLE IF NOT EXISTS public.attendances (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id bigint NOT NULL,
  registration_id bigint, -- optional link to event_registrations.id
  user_id bigint,         -- optional link to registered user (sk_users.id)
  name text,
  email text,
  phone text,
  barangay text,
  status text DEFAULT 'Present', -- use Present/Absent/Pending (free-text, could be enum)
  marked_at timestamptz DEFAULT now() NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- Foreign keys
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints 
                 WHERE constraint_name = 'fk_attendances_event' AND table_name = 'attendances') THEN
    ALTER TABLE public.attendances
      ADD CONSTRAINT fk_attendances_event
      FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints 
                 WHERE constraint_name = 'fk_attendances_registration' AND table_name = 'attendances') THEN
    ALTER TABLE public.attendances
      ADD CONSTRAINT fk_attendances_registration
      FOREIGN KEY (registration_id) REFERENCES public.event_registrations(id) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints 
                 WHERE constraint_name = 'fk_attendances_user' AND table_name = 'attendances') THEN
    ALTER TABLE public.attendances
      ADD CONSTRAINT fk_attendances_user
      FOREIGN KEY (user_id) REFERENCES public.sk_users(id);
  END IF;
END $$;

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_attendances_event_id ON public.attendances (event_id);
CREATE INDEX IF NOT EXISTS idx_attendances_user_id ON public.attendances (user_id);
CREATE INDEX IF NOT EXISTS idx_attendances_marked_at ON public.attendances (marked_at);

-- Example queries / sanity checks (uncomment to run)
-- SELECT * FROM public.event_registrations ORDER BY registered_at DESC LIMIT 5;
-- SELECT * FROM public.attendances ORDER BY marked_at DESC LIMIT 10;

-- End of migration
