-- Optional: Create event_qr_tokens table for storing generated QR tokens
-- Run this in Supabase SQL editor if you want to track which tokens were generated for which events

CREATE TABLE IF NOT EXISTS public.event_qr_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id bigint NOT NULL,
  qr_token text NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now() NOT NULL,
  active boolean DEFAULT true,
  generated_by bigint, -- optional: admin user who generated
  FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_event_qr_tokens_event_id ON public.event_qr_tokens (event_id);
CREATE INDEX IF NOT EXISTS idx_event_qr_tokens_token ON public.event_qr_tokens (qr_token);

-- Add qr_token column to events table if it doesn't exist (optional)
-- ALTER TABLE public.events ADD COLUMN IF NOT EXISTS qr_token text;
-- CREATE INDEX IF NOT EXISTS idx_events_qr_token ON public.events (qr_token);
